# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Marcos André\Documents\Programas em python\Aplicações Python\Pyqt5 aplicações\Agenda_Tela_Edicao.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Edicao(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(621, 566)
        MainWindow.setStyleSheet("background-color: rgb(0, 109, 163);\n"
"font: 75 12pt \"Times New Roman\";")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(120, 130, 141, 31))
        self.label.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(120, 180, 141, 31))
        self.label_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.DataL = QtWidgets.QLineEdit(self.centralwidget)
        self.DataL.setGeometry(QtCore.QRect(270, 180, 201, 31))
        self.DataL.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.DataL.setObjectName("DataL")
        self.AssuntoL_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.AssuntoL_2.setGeometry(QtCore.QRect(270, 130, 201, 31))
        self.AssuntoL_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.AssuntoL_2.setText("")
        self.AssuntoL_2.setObjectName("AssuntoL_2")
        self.EditarB = QtWidgets.QPushButton(self.centralwidget)
        self.EditarB.setGeometry(QtCore.QRect(130, 320, 141, 31))
        self.EditarB.setStyleSheet("background-color: rgb(52, 156, 76);")
        self.EditarB.setObjectName("EditarB")
        self.VoltarB = QtWidgets.QPushButton(self.centralwidget)
        self.VoltarB.setGeometry(QtCore.QRect(300, 320, 141, 31))
        self.VoltarB.setStyleSheet("background-color: rgb(52, 156, 76);")
        self.VoltarB.setObjectName("VoltarB")
        self.PesquisarL_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.PesquisarL_2.setGeometry(QtCore.QRect(120, 80, 191, 31))
        self.PesquisarL_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.PesquisarL_2.setObjectName("PesquisarL_2")
        self.PesquisarB_2 = QtWidgets.QPushButton(self.centralwidget)
        self.PesquisarB_2.setGeometry(QtCore.QRect(320, 80, 111, 31))
        self.PesquisarB_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.PesquisarB_2.setObjectName("PesquisarB_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(120, 45, 181, 21))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Assunto:"))
        self.label_2.setText(_translate("MainWindow", "Prazo:"))
        self.DataL.setText(_translate("MainWindow", "2000/01/01"))
        self.EditarB.setText(_translate("MainWindow", "Editar"))
        self.VoltarB.setText(_translate("MainWindow", "Voltar"))
        self.PesquisarB_2.setText(_translate("MainWindow", "Pesquisar"))
        self.label_3.setText(_translate("MainWindow", "Código do compromisso"))

if __name__ == "__main__":
        import sys
        app = QtWidgets.QApplication(sys.argv)
        MainWindow = QtWidgets.QMainWindow()
        ui = Ui_Edicao()
        ui.setupUi(MainWindow)
        MainWindow.show()
        sys.exit(app.exec_())