# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Marcos André\Documents\Programas em python\Aplicações Python\Pyqt5 aplicações\Agenda_Tela_Principal.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Principal(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(631, 573)
        MainWindow.setStyleSheet("font: 75 12pt \"Times New Roman\";\n"
"background-color: rgb(0, 108, 162);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.PesquisarL = QtWidgets.QLineEdit(self.centralwidget)
        self.PesquisarL.setGeometry(QtCore.QRect(60, 60, 191, 31))
        self.PesquisarL.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.PesquisarL.setObjectName("PesquisarL")
        self.PesquisarB = QtWidgets.QPushButton(self.centralwidget)
        self.PesquisarB.setGeometry(QtCore.QRect(260, 60, 111, 31))
        self.PesquisarB.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.PesquisarB.setObjectName("PesquisarB")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(60, 40, 181, 16))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(110, 120, 401, 361))
        self.tableWidget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        self.AdicionarB = QtWidgets.QPushButton(self.centralwidget)
        self.AdicionarB.setGeometry(QtCore.QRect(140, 490, 101, 31))
        self.AdicionarB.setStyleSheet("background-color: rgb(0, 162, 78);")
        self.AdicionarB.setObjectName("AdicionarB")
        self.EditarB = QtWidgets.QPushButton(self.centralwidget)
        self.EditarB.setGeometry(QtCore.QRect(250, 490, 121, 31))
        self.EditarB.setStyleSheet("background-color: rgb(132, 107, 175);")
        self.EditarB.setObjectName("EditarB")
        self.ExcluirB = QtWidgets.QPushButton(self.centralwidget)
        self.ExcluirB.setGeometry(QtCore.QRect(380, 490, 101, 31))
        self.ExcluirB.setStyleSheet("background-color: rgb(170, 0, 0);")
        self.ExcluirB.setObjectName("ExcluirB")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.PesquisarB.setText(_translate("MainWindow", "Pesquisar"))
        self.label.setText(_translate("MainWindow", "Pesquise por Assunto"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Código"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Inicío"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Conclusão em"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Assunto"))
        self.AdicionarB.setText(_translate("MainWindow", "Adicionar"))
        self.EditarB.setText(_translate("MainWindow", "Editar"))
        self.ExcluirB.setText(_translate("MainWindow", "Excluir"))

if __name__ == "__main__":
        import sys
        app = QtWidgets.QApplication(sys.argv)
        MainWindow = QtWidgets.QMainWindow()
        ui = Ui_Principal()
        ui.setupUi(MainWindow)
        MainWindow.show()
        sys.exit(app.exec_())