# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Marcos André\Documents\Programas em python\Aplicações Python\Pyqt5 aplicações\Tela_Update.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Atualizar(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(545, 532)
        MainWindow.setStyleSheet("background-color: rgb(0, 182, 88);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.AplicarB = QtWidgets.QPushButton(self.centralwidget)
        self.AplicarB.setGeometry(QtCore.QRect(200, 430, 151, 41))
        self.AplicarB.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 58, 176);\n"
"font: 75 12pt \"Times New Roman\";")
        self.AplicarB.setObjectName("AplicarB")
        self.PesquisarID = QtWidgets.QPushButton(self.centralwidget)
        self.PesquisarID.setGeometry(QtCore.QRect(300, 10, 151, 41))
        self.PesquisarID.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 58, 176);\n"
"font: 75 12pt \"Times New Roman\";")
        self.PesquisarID.setObjectName("PesquisarID")
        self.IDL = QtWidgets.QLineEdit(self.centralwidget)
        self.IDL.setGeometry(QtCore.QRect(102, 10, 181, 41))
        self.IDL.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.IDL.setObjectName("IDL")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(180, 60, 151, 31))
        self.label.setStyleSheet("font: 75 14pt \"Times New Roman\";\n"
"background-color: rgb(52, 156, 76);\n"
"color: rgb(255, 255, 255);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.NomeA = QtWidgets.QLineEdit(self.centralwidget)
        self.NomeA.setEnabled(True)
        self.NomeA.setGeometry(QtCore.QRect(180, 140, 151, 31))
        self.NomeA.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.NomeA.setObjectName("NomeA")
        self.DescricaoA = QtWidgets.QLineEdit(self.centralwidget)
        self.DescricaoA.setEnabled(True)
        self.DescricaoA.setGeometry(QtCore.QRect(180, 180, 151, 31))
        self.DescricaoA.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.DescricaoA.setObjectName("DescricaoA")
        self.CpfA = QtWidgets.QLineEdit(self.centralwidget)
        self.CpfA.setEnabled(True)
        self.CpfA.setGeometry(QtCore.QRect(180, 220, 151, 31))
        self.CpfA.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.CpfA.setObjectName("CpfA")
        self.SalarioA = QtWidgets.QLineEdit(self.centralwidget)
        self.SalarioA.setEnabled(True)
        self.SalarioA.setGeometry(QtCore.QRect(180, 260, 151, 31))
        self.SalarioA.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.SalarioA.setObjectName("SalarioA")
        self.LojaA = QtWidgets.QLineEdit(self.centralwidget)
        self.LojaA.setEnabled(True)
        self.LojaA.setGeometry(QtCore.QRect(180, 300, 151, 31))
        self.LojaA.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.LojaA.setObjectName("LojaA")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 140, 81, 31))
        self.label_3.setStyleSheet("font: 75 14pt \"Times New Roman\";\n"
"background-color: rgb(52, 156, 76);\n"
"color: rgb(255, 255, 255);")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 180, 81, 31))
        self.label_4.setStyleSheet("font: 75 14pt \"Times New Roman\";\n"
"background-color: rgb(52, 156, 76);\n"
"color: rgb(255, 255, 255);")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(10, 220, 81, 31))
        self.label_5.setStyleSheet("font: 75 14pt \"Times New Roman\";\n"
"background-color: rgb(52, 156, 76);\n"
"color: rgb(255, 255, 255);")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(10, 260, 81, 31))
        self.label_6.setStyleSheet("font: 75 14pt \"Times New Roman\";\n"
"background-color: rgb(52, 156, 76);\n"
"color: rgb(255, 255, 255);")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(10, 300, 81, 31))
        self.label_7.setStyleSheet("font: 75 14pt \"Times New Roman\";\n"
"background-color: rgb(52, 156, 76);\n"
"color: rgb(255, 255, 255);")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.IdA = QtWidgets.QLineEdit(self.centralwidget)
        self.IdA.setEnabled(False)
        self.IdA.setGeometry(QtCore.QRect(180, 100, 151, 31))
        self.IdA.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.IdA.setObjectName("IdA")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.AplicarB.setText(_translate("MainWindow", "Aplicar Atualizações"))
        self.PesquisarID.setText(_translate("MainWindow", "Pesquisar por Id"))
        self.label.setText(_translate("MainWindow", "Atualizar"))
        self.label_3.setText(_translate("MainWindow", "Nome"))
        self.label_4.setText(_translate("MainWindow", "Desc"))
        self.label_5.setText(_translate("MainWindow", "Cpf"))
        self.label_6.setText(_translate("MainWindow", "Salário"))
        self.label_7.setText(_translate("MainWindow", "Loja"))

if __name__ == "__main__":
        import sys
        app = QtWidgets.QApplication(sys.argv)
        MainWindow = QtWidgets.QMainWindow()
        ui = Ui_Atualizar()
        ui.setupUi(MainWindow)
        MainWindow.show()
        sys.exit(app.exec_())