# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Marcos André\Documents\Programas em python\Aplicações Python\Pyqt5 aplicações\Tela_Login.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Login(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(568, 543)
        MainWindow.setStyleSheet("font: 75 14pt \"Times New Roman\";\n"
"background-color: rgb(58, 58, 176);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.loginL = QtWidgets.QLineEdit(self.centralwidget)
        self.loginL.setGeometry(QtCore.QRect(160, 150, 231, 31))
        self.loginL.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.loginL.setObjectName("loginL")
        self.Logar = QtWidgets.QPushButton(self.centralwidget)
        self.Logar.setGeometry(QtCore.QRect(220, 290, 111, 31))
        self.Logar.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Logar.setObjectName("Logar")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(220, 200, 111, 16))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.senhaL = QtWidgets.QLineEdit(self.centralwidget)
        self.senhaL.setGeometry(QtCore.QRect(160, 230, 231, 31))
        self.senhaL.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.senhaL.setEchoMode(QtWidgets.QLineEdit.Password)
        self.senhaL.setObjectName("senhaL")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(220, 110, 111, 21))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(120, 50, 311, 21))
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Logar.setText(_translate("MainWindow", "Logar"))
        self.label.setText(_translate("MainWindow", "Senha"))
        self.label_2.setText(_translate("MainWindow", "Login"))
        self.label_3.setText(_translate("MainWindow", "Bem vindo!"))


if __name__ == "__main__":
        import sys
        app = QtWidgets.QApplication(sys.argv)
        MainWindow = QtWidgets.QMainWindow()
        ui = Ui_Login()
        ui.setupUi(MainWindow)
        MainWindow.show()
        sys.exit(app.exec_())